### PR TITLE
refactor: revert the pre-serialization and parallel buffer

### LINKED ISSUE #708: perf: performance regression on RisingWave with 0.11
There is an obvious regression on nexmark Q7 and Q014 for RisingWave with foyer 0.11 rather than with foyer 0.10.

image

Based on the flamegraph, the regression comes from 3 stacks:

image

Which are:

image

and

image

and

image

Let's see why.

Full flamegraphs:

rw 010

rw 011

Grafana:

010: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=cdtasocg64074c&var-namespace=xx-foyer-010-1&var-instance=benchmark-risingwave&var-pod=All&var-component=All&var-table=All&from=1726042331594&to=1726086587137
011: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=cdtasocg64074c&var-namespace=xx-foyer-011-1&var-instance=benchmark-risingwave&var-pod=All&var-component=All&var-table=All&from=1726041953341&to=1726086965390

### PR DESCRIPTION
**Pull request by MrCroxx**
## What's changed and what's your intention?

> Please explain **IN DETAIL** what the changes are in this PR and why they are needed. :D

Let's revert the pre-serialization and parallel buffer design to resolve the memory usage overhead.

## Checklist

- [x] I have written the necessary rustdoc comments
- [x] I have added the necessary unit tests and integration tests
- [x] I have passed `make all` (or `make fast` instead if the old tests are not modified) in my local environment.

## Related issues or PRs (optional)
close #708

### CODE REVIEW

**Comment by MrCroxx** [comment]
# Benchmark

## command

```bash
cargo build --release --features jemalloc && PATH=/home/mrcroxx/.local/bin:$PATH RUST_BACKTRACE=1 RUST_LOG=info flamegraph -- ./target/release/foyer-bench --file /dev/nvme2n1 --mem 64MiB --disk 100GiB --region-size 64MiB --get-range 100000 --flushers 4 --reclaimers 4 --time 60 --writers 256 --w-rate 4MiB --admission-rate-limit 500MiB --readers 32 --r-rate 32MiB --metrics --warm-up 2 --runtime separated --user-runtime-worker-threads 8 --read-runtime-worker-threads 8 --write-runtime-worker-threads 4 --read-runtime-max-blocking-threads 8 --write-runtime-max-blocking-threads 4
```

## main

```
Total:
disk total iops: 16007.2
disk total throughput: 1.5 GiB/s
disk read iops: 14971.7
disk read throughput: 1.0 GiB/s
disk write iops: 1035.5
disk write throughput: 498.8 MiB/s
insert iops: 15859.0/s
insert throughput: 1.0 GiB/s
insert lat p50: 4us
insert lat p90: 8us
insert lat p99: 14us
insert lat p999: 28us
insert lat p9999: 68us
insert lat p99999: 214us
insert lat pmax: 475us
get iops: 45936.5/s
get miss: 65.49% 
get throughput: 1.0 GiB/s
get hit lat p50: 299us
get hit lat p90: 627us
get hit lat p99: 2239us
get hit lat p999: 2815us
get hit lat p9999: 3167us
get hit lat p99999: 3519us
get hit lat pmax: 4063us
get miss lat p50: 15us
get miss lat p90: 30us
get miss lat p99: 68us
get miss lat p999: 213us
get miss lat p9999: 309us
get miss lat p99999: 461us
get miss lat pmax: 639us
```

## PR

```
Total:
disk total iops: 22340.9
disk total throughput: 1.4 GiB/s
disk read iops: 14871.8
disk read throughput: 1.0 GiB/s
disk write iops: 7469.0
disk write throughput: 496.0 MiB/s
insert iops: 15858.9/s
insert throughput: 1.0 GiB/s
insert lat p50: 3us
insert lat p90: 6us
insert lat p99: 11us
insert lat p999: 23us
insert lat p9999: 59us
insert lat p99999: 263us
insert lat pmax: 507us
get iops: 49758.2/s
get miss: 68.14% 
get throughput: 1.0 GiB/s
get hit lat p50: 291us
get hit lat p90: 631us
get hit lat p99: 2191us
get hit lat p999: 2751us
get hit lat p9999: 3279us
get hit lat p99999: 5663us
get hit lat pmax: 6367us
get miss lat p50: 14us
get miss lat p90: 28us
get miss lat p99: 62us
get miss lat p999: 150us
get miss lat p9999: 303us
get miss lat p99999: 503us
get miss lat pmax: 1191us
```

**Comment by hzxa21** [comment]
The disk write iops increases from 1035.5 to 7469.0 with similar disk throughput and insert iops. Is this expected?

**Comment by MrCroxx** [comment]
> The disk write iops increases from 1035.5 to 7469.0 with similar disk throughput and insert iops. Is this expected?

Yes. The disk hit ratio also increased. I'm still checking the reason.

**Comment by MrCroxx** [comment]
DIscussed with @st1page offline. Let's merge it.

**Pull request merged**
